/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CPUStats,
    CPUStatsFromJSON,
    CPUStatsFromJSONTyped,
    CPUStatsToJSON,
    Job,
    JobFromJSON,
    JobFromJSONTyped,
    JobToJSON,
    PauseState,
    PauseStateFromJSON,
    PauseStateFromJSONTyped,
    PauseStateToJSON,
    RenderQueueItem,
    RenderQueueItemFromJSON,
    RenderQueueItemFromJSONTyped,
    RenderQueueItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface AeRendererState
 */
export interface AeRendererState {
    /**
     * 
     * @type {string}
     * @memberof AeRendererState
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AeRendererState
     */
    settings?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AeRendererState
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AeRendererState
     */
    isDone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AeRendererState
     */
    frameRate?: string | null;
    /**
     * 
     * @type {Array<Job>}
     * @memberof AeRendererState
     */
    jobs?: Array<Job> | null;
    /**
     * 
     * @type {Array<RenderQueueItem>}
     * @memberof AeRendererState
     */
    queue?: Array<RenderQueueItem> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AeRendererState
     */
    scheduledQueueItems?: Array<string> | null;
    /**
     * 
     * @type {CPUStats}
     * @memberof AeRendererState
     */
    renderCPUStats?: CPUStats;
    /**
     * 
     * @type {PauseState}
     * @memberof AeRendererState
     */
    pause?: PauseState;
}

export function AeRendererStateFromJSON(json: any): AeRendererState {
    return AeRendererStateFromJSONTyped(json, false);
}

export function AeRendererStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AeRendererState {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'settings': !exists(json, 'Settings') ? undefined : json['Settings'],
        'errorMessage': !exists(json, 'ErrorMessage') ? undefined : json['ErrorMessage'],
        'isDone': !exists(json, 'isDone') ? undefined : json['isDone'],
        'frameRate': !exists(json, 'FrameRate') ? undefined : json['FrameRate'],
        'jobs': !exists(json, 'Jobs') ? undefined : (json['Jobs'] === null ? null : (json['Jobs'] as Array<any>).map(JobFromJSON)),
        'queue': !exists(json, 'Queue') ? undefined : (json['Queue'] === null ? null : (json['Queue'] as Array<any>).map(RenderQueueItemFromJSON)),
        'scheduledQueueItems': !exists(json, 'ScheduledQueueItems') ? undefined : json['ScheduledQueueItems'],
        'renderCPUStats': !exists(json, 'RenderCPUStats') ? undefined : CPUStatsFromJSON(json['RenderCPUStats']),
        'pause': !exists(json, 'Pause') ? undefined : PauseStateFromJSON(json['Pause']),
    };
}

export function AeRendererStateToJSON(value?: AeRendererState | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Settings': value.settings,
        'ErrorMessage': value.errorMessage,
        'isDone': value.isDone,
        'FrameRate': value.frameRate,
        'Jobs': value.jobs === undefined ? undefined : (value.jobs === null ? null : (value.jobs as Array<any>).map(JobToJSON)),
        'Queue': value.queue === undefined ? undefined : (value.queue === null ? null : (value.queue as Array<any>).map(RenderQueueItemToJSON)),
        'ScheduledQueueItems': value.scheduledQueueItems,
        'RenderCPUStats': CPUStatsToJSON(value.renderCPUStats),
        'Pause': PauseStateToJSON(value.pause),
    };
}


