/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiOperationResult
 */
export interface ApiOperationResult {
    /**
     * 
     * @type {string}
     * @memberof ApiOperationResult
     */
    result?: string | null;
}

export function ApiOperationResultFromJSON(json: any): ApiOperationResult {
    return ApiOperationResultFromJSONTyped(json, false);
}

export function ApiOperationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiOperationResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : json['result'],
    };
}

export function ApiOperationResultToJSON(value?: ApiOperationResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
    };
}


