/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BGRendererArgs,
    BGRendererArgsFromJSON,
    BGRendererArgsFromJSONTyped,
    BGRendererArgsToJSON,
} from './';

/**
 * 
 * @export
 * @interface BGRendererInput
 */
export interface BGRendererInput {
    /**
     * 
     * @type {Array<BGRendererArgs>}
     * @memberof BGRendererInput
     */
    payload?: Array<BGRendererArgs> | null;
}

export function BGRendererInputFromJSON(json: any): BGRendererInput {
    return BGRendererInputFromJSONTyped(json, false);
}

export function BGRendererInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BGRendererInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'payload': !exists(json, 'payload') ? undefined : (json['payload'] === null ? null : (json['payload'] as Array<any>).map(BGRendererArgsFromJSON)),
    };
}

export function BGRendererInputToJSON(value?: BGRendererInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'payload': value.payload === undefined ? undefined : (value.payload === null ? null : (value.payload as Array<any>).map(BGRendererArgsToJSON)),
    };
}


