/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    project?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    path?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    frame?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    parentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    isDone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    rQItemAssigned?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    compName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    compDuration?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    startFrame?: string | null;
}

export function JobFromJSON(json: any): Job {
    return JobFromJSONTyped(json, false);
}

export function JobFromJSONTyped(json: any, ignoreDiscriminator: boolean): Job {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'project': !exists(json, 'Project') ? undefined : json['Project'],
        'path': !exists(json, 'Path') ? undefined : json['Path'],
        'frame': !exists(json, 'Frame') ? undefined : json['Frame'],
        'parentId': !exists(json, 'ParentId') ? undefined : json['ParentId'],
        'isDone': !exists(json, 'IsDone') ? undefined : json['IsDone'],
        'rQItemAssigned': !exists(json, 'RQItemAssigned') ? undefined : json['RQItemAssigned'],
        'compName': !exists(json, 'CompName') ? undefined : json['CompName'],
        'compDuration': !exists(json, 'CompDuration') ? undefined : json['CompDuration'],
        'startFrame': !exists(json, 'StartFrame') ? undefined : json['StartFrame'],
    };
}

export function JobToJSON(value?: Job | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Project': value.project,
        'Path': value.path,
        'Frame': value.frame,
        'ParentId': value.parentId,
        'IsDone': value.isDone,
        'RQItemAssigned': value.rQItemAssigned,
        'CompName': value.compName,
        'CompDuration': value.compDuration,
        'StartFrame': value.startFrame,
    };
}


