/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    project?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    path?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    frame?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    parentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    isDone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    rQItemAssigned?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    compName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    compDuration?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    startFrame?: string | null;
}

export function JobFromJSON(json: any): Job {
    return JobFromJSONTyped(json, false);
}

export function JobFromJSONTyped(json: any, ignoreDiscriminator: boolean): Job {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'project': !exists(json, 'project') ? undefined : json['project'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'frame': !exists(json, 'frame') ? undefined : json['frame'],
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
        'isDone': !exists(json, 'isDone') ? undefined : json['isDone'],
        'rQItemAssigned': !exists(json, 'rQItemAssigned') ? undefined : json['rQItemAssigned'],
        'compName': !exists(json, 'compName') ? undefined : json['compName'],
        'compDuration': !exists(json, 'compDuration') ? undefined : json['compDuration'],
        'startFrame': !exists(json, 'startFrame') ? undefined : json['startFrame'],
    };
}

export function JobToJSON(value?: Job | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'project': value.project,
        'path': value.path,
        'frame': value.frame,
        'parentId': value.parentId,
        'isDone': value.isDone,
        'rQItemAssigned': value.rQItemAssigned,
        'compName': value.compName,
        'compDuration': value.compDuration,
        'startFrame': value.startFrame,
    };
}


