/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    JsonValueKind,
    JsonValueKindFromJSON,
    JsonValueKindFromJSONTyped,
    JsonValueKindToJSON,
} from './';

/**
 * 
 * @export
 * @interface JsonElement
 */
export interface JsonElement {
    /**
     * 
     * @type {JsonValueKind}
     * @memberof JsonElement
     */
    valueKind?: JsonValueKind;
}

export function JsonElementFromJSON(json: any): JsonElement {
    return JsonElementFromJSONTyped(json, false);
}

export function JsonElementFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonElement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'valueKind': !exists(json, 'valueKind') ? undefined : JsonValueKindFromJSON(json['valueKind']),
    };
}

export function JsonElementToJSON(value?: JsonElement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'valueKind': JsonValueKindToJSON(value.valueKind),
    };
}


