/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum JsonValueKind {
    Undefined = 'Undefined',
    Object = 'Object',
    Array = 'Array',
    String = 'String',
    Number = 'Number',
    True = 'True',
    False = 'False',
    Null = 'Null'
}

export function JsonValueKindFromJSON(json: any): JsonValueKind {
    return JsonValueKindFromJSONTyped(json, false);
}

export function JsonValueKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonValueKind {
    return json as JsonValueKind;
}

export function JsonValueKindToJSON(value?: JsonValueKind | null): any {
    return value as any;
}

