/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MirrorService
 */
export interface MirrorService {
    /**
     * 
     * @type {boolean}
     * @memberof MirrorService
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MirrorService
     */
    serverUrl?: string | null;
}

export function MirrorServiceFromJSON(json: any): MirrorService {
    return MirrorServiceFromJSONTyped(json, false);
}

export function MirrorServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MirrorService {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isActive': !exists(json, 'isActive') ? undefined : json['isActive'],
        'serverUrl': !exists(json, 'serverUrl') ? undefined : json['serverUrl'],
    };
}

export function MirrorServiceToJSON(value?: MirrorService | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isActive': value.isActive,
        'serverUrl': value.serverUrl,
    };
}


