/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NetworkRenderJoinGroupOperation
 */
export interface NetworkRenderJoinGroupOperation {
    /**
     * 
     * @type {string}
     * @memberof NetworkRenderJoinGroupOperation
     */
    apiUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NetworkRenderJoinGroupOperation
     */
    groupId?: string | null;
}

export function NetworkRenderJoinGroupOperationFromJSON(json: any): NetworkRenderJoinGroupOperation {
    return NetworkRenderJoinGroupOperationFromJSONTyped(json, false);
}

export function NetworkRenderJoinGroupOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkRenderJoinGroupOperation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiUrl': !exists(json, 'apiUrl') ? undefined : json['apiUrl'],
        'groupId': !exists(json, 'groupId') ? undefined : json['groupId'],
    };
}

export function NetworkRenderJoinGroupOperationToJSON(value?: NetworkRenderJoinGroupOperation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiUrl': value.apiUrl,
        'groupId': value.groupId,
    };
}


