/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PauseOperation,
    PauseOperationFromJSON,
    PauseOperationFromJSONTyped,
    PauseOperationToJSON,
} from './';

/**
 * 
 * @export
 * @interface PauseOperationPayload
 */
export interface PauseOperationPayload {
    /**
     * 
     * @type {PauseOperation}
     * @memberof PauseOperationPayload
     */
    pauseOperation?: PauseOperation;
}

export function PauseOperationPayloadFromJSON(json: any): PauseOperationPayload {
    return PauseOperationPayloadFromJSONTyped(json, false);
}

export function PauseOperationPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PauseOperationPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pauseOperation': !exists(json, 'pauseOperation') ? undefined : PauseOperationFromJSON(json['pauseOperation']),
    };
}

export function PauseOperationPayloadToJSON(value?: PauseOperationPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pauseOperation': PauseOperationToJSON(value.pauseOperation),
    };
}


