/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PauseProcessState {
    NotApplied = 'NotApplied',
    Paused = 'Paused',
    Pausing = 'Pausing',
    Continuing = 'Continuing'
}

export function PauseProcessStateFromJSON(json: any): PauseProcessState {
    return PauseProcessStateFromJSONTyped(json, false);
}

export function PauseProcessStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PauseProcessState {
    return json as PauseProcessState;
}

export function PauseProcessStateToJSON(value?: PauseProcessState | null): any {
    return value as any;
}

