/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PauseProcessControllable {
    Denied = 'Denied',
    Allowed = 'Allowed'
}

export function PauseProcessControllableFromJSON(json: any): PauseProcessControllable {
    return PauseProcessControllableFromJSONTyped(json, false);
}

export function PauseProcessControllableFromJSONTyped(json: any, ignoreDiscriminator: boolean): PauseProcessControllable {
    return json as PauseProcessControllable;
}

export function PauseProcessControllableToJSON(value?: PauseProcessControllable | null): any {
    return value as any;
}

