/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    JsonElement,
    JsonElementFromJSON,
    JsonElementFromJSONTyped,
    JsonElementToJSON,
    PostRenderState,
    PostRenderStateFromJSON,
    PostRenderStateFromJSONTyped,
    PostRenderStateToJSON,
} from './';

/**
 * 
 * @export
 * @interface PostRender
 */
export interface PostRender {
    /**
     * 
     * @type {string}
     * @memberof PostRender
     */
    type?: string | null;
    /**
     * 
     * @type {PostRenderState}
     * @memberof PostRender
     */
    state?: PostRenderState;
    /**
     * 
     * @type {string}
     * @memberof PostRender
     */
    progress?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PostRender
     */
    args?: Array<string> | null;
    /**
     * 
     * @type {JsonElement}
     * @memberof PostRender
     */
    settings?: JsonElement;
}

export function PostRenderFromJSON(json: any): PostRender {
    return PostRenderFromJSONTyped(json, false);
}

export function PostRenderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostRender {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'Type') ? undefined : json['Type'],
        'state': !exists(json, 'State') ? undefined : PostRenderStateFromJSON(json['State']),
        'progress': !exists(json, 'Progress') ? undefined : json['Progress'],
        'args': !exists(json, 'Args') ? undefined : json['Args'],
        'settings': !exists(json, 'Settings') ? undefined : JsonElementFromJSON(json['Settings']),
    };
}

export function PostRenderToJSON(value?: PostRender | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Type': value.type,
        'State': PostRenderStateToJSON(value.state),
        'Progress': value.progress,
        'Args': value.args,
        'Settings': JsonElementToJSON(value.settings),
    };
}


