/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PostRenderState {
    Scheduled = 'Scheduled',
    Started = 'Started',
    Finished = 'Finished',
    Error = 'Error'
}

export function PostRenderStateFromJSON(json: any): PostRenderState {
    return PostRenderStateFromJSONTyped(json, false);
}

export function PostRenderStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostRenderState {
    return json as PostRenderState;
}

export function PostRenderStateToJSON(value?: PostRenderState | null): any {
    return value as any;
}

