/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PreRenderState,
    PreRenderStateFromJSON,
    PreRenderStateFromJSONTyped,
    PreRenderStateToJSON,
} from './';

/**
 * 
 * @export
 * @interface PreRender
 */
export interface PreRender {
    /**
     * 
     * @type {string}
     * @memberof PreRender
     */
    type?: string | null;
    /**
     * 
     * @type {PreRenderState}
     * @memberof PreRender
     */
    state?: PreRenderState;
    /**
     * 
     * @type {string}
     * @memberof PreRender
     */
    progress?: string | null;
    /**
     * 
     * @type {object}
     * @memberof PreRender
     */
    settings?: object;
}

export function PreRenderFromJSON(json: any): PreRender {
    return PreRenderFromJSONTyped(json, false);
}

export function PreRenderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreRender {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'state': !exists(json, 'state') ? undefined : PreRenderStateFromJSON(json['state']),
        'progress': !exists(json, 'progress') ? undefined : json['progress'],
        'settings': !exists(json, 'settings') ? undefined : json['settings'],
    };
}

export function PreRenderToJSON(value?: PreRender | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'state': PreRenderStateToJSON(value.state),
        'progress': value.progress,
        'settings': value.settings,
    };
}


