/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PreRenderState {
    Scheduled = 'Scheduled',
    Started = 'Started',
    Finished = 'Finished',
    Error = 'Error'
}

export function PreRenderStateFromJSON(json: any): PreRenderState {
    return PreRenderStateFromJSONTyped(json, false);
}

export function PreRenderStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreRenderState {
    return json as PreRenderState;
}

export function PreRenderStateToJSON(value?: PreRenderState | null): any {
    return value as any;
}

