/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RenderQueueItemRemoveOperation
 */
export interface RenderQueueItemRemoveOperation {
    /**
     * 
     * @type {string}
     * @memberof RenderQueueItemRemoveOperation
     */
    project?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RenderQueueItemRemoveOperation
     */
    path?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RenderQueueItemRemoveOperation
     */
    compName?: string | null;
}

export function RenderQueueItemRemoveOperationFromJSON(json: any): RenderQueueItemRemoveOperation {
    return RenderQueueItemRemoveOperationFromJSONTyped(json, false);
}

export function RenderQueueItemRemoveOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenderQueueItemRemoveOperation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'project': !exists(json, 'project') ? undefined : json['project'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'compName': !exists(json, 'compName') ? undefined : json['compName'],
    };
}

export function RenderQueueItemRemoveOperationToJSON(value?: RenderQueueItemRemoveOperation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'project': value.project,
        'path': value.path,
        'compName': value.compName,
    };
}


