/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PostRender,
    PostRenderFromJSON,
    PostRenderFromJSONTyped,
    PostRenderToJSON,
    PreRender,
    PreRenderFromJSON,
    PreRenderFromJSONTyped,
    PreRenderToJSON,
} from './';

/**
 * 
 * @export
 * @interface RenderQueueItem
 */
export interface RenderQueueItem {
    /**
     * 
     * @type {string}
     * @memberof RenderQueueItem
     */
    rqNum?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RenderQueueItem
     */
    threadsInProgress?: number;
    /**
     * 
     * @type {number}
     * @memberof RenderQueueItem
     */
    threadsFinished?: number;
    /**
     * 
     * @type {string}
     * @memberof RenderQueueItem
     */
    isDone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RenderQueueItem
     */
    hasError?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RenderQueueItem
     */
    project?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RenderQueueItem
     */
    path?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RenderQueueItem
     */
    compName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RenderQueueItem
     */
    compDuration?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RenderQueueItem
     */
    startFrame?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RenderQueueItem
     */
    frameRate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RenderQueueItem
     */
    startTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RenderQueueItem
     */
    endTime?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RenderQueueItem
     */
    maxThreads?: number;
    /**
     * 
     * @type {Array<PostRender>}
     * @memberof RenderQueueItem
     */
    postRenders?: Array<PostRender> | null;
    /**
     * 
     * @type {Array<PreRender>}
     * @memberof RenderQueueItem
     */
    preRenders?: Array<PreRender> | null;
}

export function RenderQueueItemFromJSON(json: any): RenderQueueItem {
    return RenderQueueItemFromJSONTyped(json, false);
}

export function RenderQueueItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenderQueueItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rqNum': !exists(json, 'RqNum') ? undefined : json['RqNum'],
        'threadsInProgress': !exists(json, 'ThreadsInProgress') ? undefined : json['ThreadsInProgress'],
        'threadsFinished': !exists(json, 'ThreadsFinished') ? undefined : json['ThreadsFinished'],
        'isDone': !exists(json, 'IsDone') ? undefined : json['IsDone'],
        'hasError': !exists(json, 'HasError') ? undefined : json['HasError'],
        'project': !exists(json, 'Project') ? undefined : json['Project'],
        'path': !exists(json, 'Path') ? undefined : json['Path'],
        'compName': !exists(json, 'CompName') ? undefined : json['CompName'],
        'compDuration': !exists(json, 'CompDuration') ? undefined : json['CompDuration'],
        'startFrame': !exists(json, 'StartFrame') ? undefined : json['StartFrame'],
        'frameRate': !exists(json, 'FrameRate') ? undefined : json['FrameRate'],
        'startTime': !exists(json, 'StartTime') ? undefined : json['StartTime'],
        'endTime': !exists(json, 'EndTime') ? undefined : json['EndTime'],
        'maxThreads': !exists(json, 'MaxThreads') ? undefined : json['MaxThreads'],
        'postRenders': !exists(json, 'PostRenders') ? undefined : (json['PostRenders'] === null ? null : (json['PostRenders'] as Array<any>).map(PostRenderFromJSON)),
        'preRenders': !exists(json, 'PreRenders') ? undefined : (json['PreRenders'] === null ? null : (json['PreRenders'] as Array<any>).map(PreRenderFromJSON)),
    };
}

export function RenderQueueItemToJSON(value?: RenderQueueItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RqNum': value.rqNum,
        'ThreadsInProgress': value.threadsInProgress,
        'ThreadsFinished': value.threadsFinished,
        'IsDone': value.isDone,
        'HasError': value.hasError,
        'Project': value.project,
        'Path': value.path,
        'CompName': value.compName,
        'CompDuration': value.compDuration,
        'StartFrame': value.startFrame,
        'FrameRate': value.frameRate,
        'StartTime': value.startTime,
        'EndTime': value.endTime,
        'MaxThreads': value.maxThreads,
        'PostRenders': value.postRenders === undefined ? undefined : (value.postRenders === null ? null : (value.postRenders as Array<any>).map(PostRenderToJSON)),
        'PreRenders': value.preRenders === undefined ? undefined : (value.preRenders === null ? null : (value.preRenders as Array<any>).map(PreRenderToJSON)),
    };
}


