/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RenderQueueItemRemoveOperation,
    RenderQueueItemRemoveOperationFromJSON,
    RenderQueueItemRemoveOperationFromJSONTyped,
    RenderQueueItemRemoveOperationToJSON,
} from './';

/**
 * 
 * @export
 * @interface RenderQueueItemRemovePayload
 */
export interface RenderQueueItemRemovePayload {
    /**
     * 
     * @type {RenderQueueItemRemoveOperation}
     * @memberof RenderQueueItemRemovePayload
     */
    payload?: RenderQueueItemRemoveOperation;
}

export function RenderQueueItemRemovePayloadFromJSON(json: any): RenderQueueItemRemovePayload {
    return RenderQueueItemRemovePayloadFromJSONTyped(json, false);
}

export function RenderQueueItemRemovePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenderQueueItemRemovePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'payload': !exists(json, 'payload') ? undefined : RenderQueueItemRemoveOperationFromJSON(json['payload']),
    };
}

export function RenderQueueItemRemovePayloadToJSON(value?: RenderQueueItemRemovePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'payload': RenderQueueItemRemoveOperationToJSON(value.payload),
    };
}


