/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    WsBroadcasterMessageGroupDataType,
    WsBroadcasterMessageGroupDataTypeFromJSON,
    WsBroadcasterMessageGroupDataTypeFromJSONTyped,
    WsBroadcasterMessageGroupDataTypeToJSON,
    WsBroadcasterMessageGroupOperationType,
    WsBroadcasterMessageGroupOperationTypeFromJSON,
    WsBroadcasterMessageGroupOperationTypeFromJSONTyped,
    WsBroadcasterMessageGroupOperationTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface WsBroadcasterMessage
 */
export interface WsBroadcasterMessage {
    /**
     * 
     * @type {WsBroadcasterMessageGroupOperationType}
     * @memberof WsBroadcasterMessage
     */
    groupOperation?: WsBroadcasterMessageGroupOperationType;
    /**
     * 
     * @type {WsBroadcasterMessageGroupDataType}
     * @memberof WsBroadcasterMessage
     */
    groupData?: WsBroadcasterMessageGroupDataType;
}

export function WsBroadcasterMessageFromJSON(json: any): WsBroadcasterMessage {
    return WsBroadcasterMessageFromJSONTyped(json, false);
}

export function WsBroadcasterMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): WsBroadcasterMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupOperation': !exists(json, 'groupOperation') ? undefined : WsBroadcasterMessageGroupOperationTypeFromJSON(json['groupOperation']),
        'groupData': !exists(json, 'groupData') ? undefined : WsBroadcasterMessageGroupDataTypeFromJSON(json['groupData']),
    };
}

export function WsBroadcasterMessageToJSON(value?: WsBroadcasterMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'groupOperation': WsBroadcasterMessageGroupOperationTypeToJSON(value.groupOperation),
        'groupData': WsBroadcasterMessageGroupDataTypeToJSON(value.groupData),
    };
}


