/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WsBroadcasterMessageMachineDataType
 */
export interface WsBroadcasterMessageMachineDataType {
    /**
     * 
     * @type {string}
     * @memberof WsBroadcasterMessageMachineDataType
     */
    machineName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WsBroadcasterMessageMachineDataType
     */
    machineStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WsBroadcasterMessageMachineDataType
     */
    lastReplyTime?: string | null;
}

export function WsBroadcasterMessageMachineDataTypeFromJSON(json: any): WsBroadcasterMessageMachineDataType {
    return WsBroadcasterMessageMachineDataTypeFromJSONTyped(json, false);
}

export function WsBroadcasterMessageMachineDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WsBroadcasterMessageMachineDataType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'machineName': !exists(json, 'machineName') ? undefined : json['machineName'],
        'machineStatus': !exists(json, 'machineStatus') ? undefined : json['machineStatus'],
        'lastReplyTime': !exists(json, 'lastReplyTime') ? undefined : json['lastReplyTime'],
    };
}

export function WsBroadcasterMessageMachineDataTypeToJSON(value?: WsBroadcasterMessageMachineDataType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'machineName': value.machineName,
        'machineStatus': value.machineStatus,
        'lastReplyTime': value.lastReplyTime,
    };
}


