/* tslint:disable */
/* eslint-disable */
/**
 * BgRenderer Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum WsBroadcasterMessageGroupOperationType {
    Joined = 'Joined',
    Created = 'Created',
    Left = 'Left',
    Deleted = 'Deleted'
}

export function WsBroadcasterMessageGroupOperationTypeFromJSON(json: any): WsBroadcasterMessageGroupOperationType {
    return WsBroadcasterMessageGroupOperationTypeFromJSONTyped(json, false);
}

export function WsBroadcasterMessageGroupOperationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WsBroadcasterMessageGroupOperationType {
    return json as WsBroadcasterMessageGroupOperationType;
}

export function WsBroadcasterMessageGroupOperationTypeToJSON(value?: WsBroadcasterMessageGroupOperationType | null): any {
    return value as any;
}

